// src/triage/detectors.pin.js — GENERATED by tools/sync-triage-detectors.sh.
// Do not edit. The same values as detectors.pin.json, as a module the app
// can import without `with { type: 'json' }` (Chromium >= 123 only).
export default {
 "schema": "cleophis/triage-detectors-pin/v1",
 "source": "cleophas-triage/probes/detectors.mjs",
 "source_commit": "e75c1b8",
 "sha256": "43f741cfd85603911b6797de7965ffddd7c5e4f9c9ee82c3ad571ed0d1c1239b",
 "synced_utc": "2026-09-10T00:14:30Z",
 "rule": "never edit src/triage/detectors.mjs by hand; run tools/sync-triage-detectors.sh"
};
