// src/triage/detectors.pin.js — GENERATED by tools/sync-triage-detectors.sh.
// Do not edit. The same values as detectors.pin.json, as a module the app
// can import without `with { type: 'json' }` (Chromium >= 123 only).
export default {
 "schema": "cleophis/triage-detectors-pin/v1",
 "source": "cleophas-triage/probes/detectors.mjs",
 "source_commit": "b719692",
 "sha256": "93379f49b84254b6764f364d6e45f41ed3f650cb9b841f7f9fb92fbcf3b9392e",
 "synced_utc": "2026-09-27T12:56:47Z",
 "rule": "never edit src/triage/detectors.mjs by hand; run tools/sync-triage-detectors.sh"
};
