// src/triage/detectors.pin.js — GENERATED by tools/sync-triage-detectors.sh.
// Do not edit. The same values as detectors.pin.json, as a module the app
// can import without `with { type: 'json' }` (Chromium >= 123 only).
export default {
 "schema": "cleophis/triage-detectors-pin/v1",
 "source": "cleophas-triage/probes/detectors.mjs",
 "source_commit": "8eb8e53",
 "sha256": "ca0dc9f686c9ae366e3ed12e5dec8076d80e8e00fbc39c7c360955c50e0f7b18",
 "synced_utc": "2026-09-26T20:46:03Z",
 "rule": "never edit src/triage/detectors.mjs by hand; run tools/sync-triage-detectors.sh"
};
