#!/usr/bin/env python3
"""gen_wordpiece_tables.py — Phase 1h Task M4b: the Unicode tables behind
`kpack_core::wordpiece`, generated from llama.cpp's own.

The bundled reference pack is chunked by token count, and the desktop
chunks with the BGE tokenizer inside llama.cpp (`kpack-embed`,
`str_to_token`). To chunk the pack exactly the same way WITHOUT linking
llama.cpp, `kpack_core::wordpiece` ports llama.cpp's WPM tokenizer, and that
tokenizer's behaviour depends on llama.cpp's Unicode tables: the one-to-one
"NFD" map, the category flags (whitespace / control / punctuation /
symbol) and the lowercase map. This script copies those tables, value for
value, from the vendored `third_party/llama-cpp-sys-2/llama.cpp/src/
unicode-data.cpp` — the exact file the desktop build compiles — into
`crates/kpack-core/src/wordpiece_tables.rs`.

    python3 tools/reference/gen_wordpiece_tables.py           # write the Rust file
    python3 tools/reference/gen_wordpiece_tables.py --check   # exit 1 if it is stale

Deterministic: the output depends only on the input file's bytes. Stdlib only.
"""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
DEFAULT_SRC = REPO / "third_party/llama-cpp-sys-2/llama.cpp/src/unicode-data.cpp"
DEFAULT_OUT = REPO / "crates/kpack-core/src/wordpiece_tables.rs"
SRC_LABEL = "third_party/llama-cpp-sys-2/llama.cpp/src/unicode-data.cpp"
PER_LINE = 6


def _block(text: str, name: str) -> str:
    m = re.search(r"\b" + re.escape(name) + r"\s*=\s*\{(.*?)\n\};", text, re.S)
    if not m:
        raise SystemExit(f"table {name} not found in the source")
    return m.group(1)


def _tuples(block: str, arity: int) -> list[tuple[int, ...]]:
    pat = r"\{\s*" + r"\s*,\s*".join([r"(0x[0-9A-Fa-f]+)"] * arity) + r"\s*\}"
    return [tuple(int(x, 16) for x in m) for m in re.findall(pat, block)]


def parse(text: str) -> dict:
    flags = _tuples(_block(text, "unicode_ranges_flags"), 2)
    ws = sorted(int(x, 16) for x in re.findall(r"0x[0-9A-Fa-f]+", _block(text, "unicode_set_whitespace")))
    lower = _tuples(_block(text, "unicode_map_lowercase"), 2)
    nfd = _tuples(_block(text, "unicode_ranges_nfd"), 3)
    # The invariants llama.cpp's own lookups rely on (unicode.cpp asserts the
    # flag table's ends; the maps are binary-searched).
    assert flags[0][0] == 0 and flags[-1][0] == 0x110000, "flag table ends"
    assert [a for a, _ in flags] == sorted({a for a, _ in flags}), "flag starts ascending"
    assert [a for a, _ in lower] == sorted({a for a, _ in lower}), "lowercase keys ascending"
    assert all(a <= b for a, b, _ in nfd) and [a for a, _, _ in nfd] == sorted({a for a, _, _ in nfd}), "nfd ranges"
    return {"flags": flags, "whitespace": ws, "lowercase": lower, "nfd": nfd}


def _rows(items: list[str]) -> str:
    lines = []
    for i in range(0, len(items), PER_LINE):
        lines.append("    " + " ".join(items[i : i + PER_LINE]))
    return "\n".join(lines)


def render(src_bytes: bytes) -> str:
    t = parse(src_bytes.decode("utf-8"))
    sha = hashlib.sha256(src_bytes).hexdigest()
    h6 = lambda v: f"0x{v:06X}"  # noqa: E731
    out = [
        "//! GENERATED by `tools/reference/gen_wordpiece_tables.py` — do not edit.",
        "//!",
        f"//! Source: `{SRC_LABEL}`",
        f"//! (sha256 {sha}),",
        "//! the llama.cpp Unicode tables the desktop's BGE tokenizer uses. Copied",
        "//! value for value so `crate::wordpiece` tokenizes exactly like llama.cpp.",
        "",
        f'pub(crate) const SOURCE_SHA256: &str = "{sha}";',
        "",
        "/// `unicode_ranges_flags`: (range start, flags); a range runs to the next start - 1.",
        "#[rustfmt::skip]",
        f"pub(crate) static FLAGS: [(u32, u16); {len(t['flags'])}] = [",
        _rows([f"({h6(a)}, 0x{b:04X})," for a, b in t["flags"]]),
        "];",
        "",
        "/// `unicode_set_whitespace`, ascending.",
        "#[rustfmt::skip]",
        f"pub(crate) static WHITESPACE: [u32; {len(t['whitespace'])}] = [",
        _rows([f"{h6(a)}," for a in t["whitespace"]]),
        "];",
        "",
        "/// `unicode_map_lowercase`: (codepoint, lowercase), ascending by codepoint.",
        "#[rustfmt::skip]",
        f"pub(crate) static LOWERCASE: [(u32, u32); {len(t['lowercase'])}] = [",
        _rows([f"({h6(a)}, {h6(b)})," for a, b in t["lowercase"]]),
        "];",
        "",
        "/// `unicode_ranges_nfd`: (first, last, the one codepoint every member maps to).",
        "#[rustfmt::skip]",
        f"pub(crate) static NFD: [(u32, u32, u32); {len(t['nfd'])}] = [",
        _rows([f"({h6(a)}, {h6(b)}, {h6(c)})," for a, b, c in t["nfd"]]),
        "];",
        "",
    ]
    return "\n".join(out)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    ap.add_argument("--src", type=Path, default=DEFAULT_SRC)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--check", action="store_true", help="exit 1 if --out differs from a fresh render")
    args = ap.parse_args(argv)
    fresh = render(args.src.read_bytes())
    if args.check:
        current = args.out.read_text(encoding="utf-8") if args.out.is_file() else ""
        if current != fresh:
            print(f"{args.out} is stale; re-run tools/reference/gen_wordpiece_tables.py", file=sys.stderr)
            return 1
        print("up to date")
        return 0
    args.out.write_text(fresh, encoding="utf-8", newline="\n")
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
