#!/usr/bin/env bash
# tools/sync-triage-detectors.sh — copy the reference detectors from the triage
# repo and record their sha. THE ONLY WAY src/triage/detectors.mjs changes.
#
#   tools/sync-triage-detectors.sh [path-to-cleophas-triage]   # default ~/cleophas-triage
#
# Refuses if the source repo's own pin (artifacts/detectors-pin.json) does not
# match the file it points at: a pin that disagrees with its file is a repo in
# the middle of an edit, and vendoring that would freeze a half-change.
#
# TWO PIN FILES, ONE RUN, ONE SET OF VALUES.
#
#   detectors.pin.json  for humans and tools — greppable, diffable, and what
#                       the exit criterion's manual check reads;
#   detectors.pin.js    for the APP, because `src/index.html` loads `app.js` as
#                       a plain ES module with no bundler, `app.js` imports
#                       `triage/guard.js` at module scope, and importing JSON
#                       from there needs `with { type: 'json' }` — an import
#                       attribute that Chromium only understands from 123 (the
#                       older `assert` spelling was removed in 126). On a
#                       minSdk-24 device whose System WebView has not updated,
#                       that one line makes `app.js` fail to PARSE, and neither
#                       build boots — the tutor's included. A generated `.js`
#                       module has no such floor.
#
# Both are written from the same dict below, so they cannot drift; the pair is
# asserted by src/triage/detectors.test.mjs. NEITHER is edited by hand.
set -euo pipefail
SRC_REPO="${1:-$HOME/cleophas-triage}"
HERE="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$SRC_REPO/probes/detectors.mjs"
PIN="$SRC_REPO/artifacts/detectors-pin.json"
DST_DIR="$HERE/src/triage"
[ -f "$SRC" ] || { echo "no $SRC — run Phase 2 Task 1 in the triage repo first"; exit 1; }
[ -f "$PIN" ] || { echo "no $PIN"; exit 1; }
actual="$(sha256sum "$SRC" | cut -d' ' -f1)"
pinned="$(python3 -c "import json,sys;print(json.load(open(sys.argv[1]))['sha256'])" "$PIN")"
[ "$actual" = "$pinned" ] || { echo "REFUSING: $SRC sha $actual != its own pin $pinned"; exit 1; }
src_head="$(git -C "$SRC_REPO" rev-parse --short HEAD)"
mkdir -p "$DST_DIR"
cp "$SRC" "$DST_DIR/detectors.mjs"
python3 - "$DST_DIR/detectors.pin.json" "$actual" "$src_head" "$DST_DIR/detectors.pin.js" <<'PY'
import json, sys, datetime
pin = {
  "schema": "cleophis/triage-detectors-pin/v1",
  "source": "cleophas-triage/probes/detectors.mjs",
  "source_commit": sys.argv[3],
  "sha256": sys.argv[2],
  "synced_utc": datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
  "rule": "never edit src/triage/detectors.mjs by hand; run tools/sync-triage-detectors.sh",
}
json.dump(pin, open(sys.argv[1], "w"), indent=1)
# The same values as a plain ES module — no import attribute, so the oldest
# WebView that runs this app can still parse `guard.js`. json.dumps emits valid
# JS object-literal syntax for this dict (string keys, string values only).
with open(sys.argv[4], "w") as f:
    f.write(
        "// src/triage/detectors.pin.js — GENERATED by tools/sync-triage-detectors.sh.\n"
        "// Do not edit. The same values as detectors.pin.json, as a module the app\n"
        "// can import without `with { type: 'json' }` (Chromium >= 123 only).\n"
        "export default " + json.dumps(pin, indent=1) + ";\n"
    )
PY
echo "vendored $SRC ($actual, $src_head) -> $DST_DIR"
echo "wrote $DST_DIR/detectors.pin.json and $DST_DIR/detectors.pin.js"
